"""attendances tablosu eklendi ilişkiler kuruldu.Serviceleri routerları yazıldı

Revision ID: 2c23d045d001
Revises: 56e9ca4f29da
Create Date: 2026-07-22 13:17:04.397235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c23d045d001'
down_revision: Union[str, Sequence[str], None] = '56e9ca4f29da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
