"""Semester tablosu foreignkey hatası düzeltildi2

Revision ID: 56e9ca4f29da
Revises: bb8e4caaadfc
Create Date: 2026-07-20 13:46:16.463028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e9ca4f29da'
down_revision: Union[str, Sequence[str], None] = 'bb8e4caaadfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
