"""xgrade midterm ve final olarak ikiye ayrıldı gerekli güncellemler yapıldı

Revision ID: 886083591a75
Revises: dc7bbdccfe09
Create Date: 2026-07-16 12:49:35.985684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886083591a75'
down_revision: Union[str, Sequence[str], None] = 'dc7bbdccfe09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('midterm_grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('final_grade', sa.Integer(), nullable=True))
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('final_grade')
        batch_op.drop_column('midterm_grade')

    # ### end Alembic commands ###
