"""UserRole enumu ekleni

Revision ID: da08b0809455
Revises: 6d30dbf4bcf4
Create Date: 2026-07-28 11:40:14.802777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da08b0809455'
down_revision: Union[str, Sequence[str], None] = '6d30dbf4bcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    userrole_enum = sa.Enum('ADMIN', 'USER', 'STUDENT', 'TEACHER', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ADMIN', 'USER', 'STUDENT', 'TEACHER', name='userrole'),
               existing_nullable=False,
               postgresql_using="upper(role)::userrole")   

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'USER', 'STUDENT', 'TEACHER', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
