"""StudentCourse tablosuna grade eklendi gerekli yerler şema ve main güncellendi

Revision ID: dc7bbdccfe09
Revises: a0558d29d64e
Create Date: 2026-07-16 12:13:22.502294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7bbdccfe09'
down_revision: Union[str, Sequence[str], None] = 'a0558d29d64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
